nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            expose_headers: ['Link', 'Authorization']
            max_age: 3600
